### ISSUE TITLE
Doesn't build atm

### ISSUE THREAD

**Issue by mxmilkiib** [harryhaaren/AutoMate#2]
```
./waf 

Setting build options & flags...
Initializing WAF build system...
Waf: Entering directory `/home/milk/src/AutoMate/build'
Building the sources to objects...
[1/8] cxx: automationwidget.cpp -> build/default/automationwidget_1.o
[2/8] cxx: automationtrack.cpp -> build/default/automationtrack_2.o
[3/8] cxx: jack.cpp -> build/default/jack_3.o
[4/8] cxx: main.cpp -> build/default/main_4.o
../automationtrack.cpp: In member function ‘float AutomationTrack::getValue()’:
../automationtrack.cpp:127:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
[5/8] static_link: build/default/automationwidget_1.o -> build/default/libautomationwidget.a
[6/8] static_link: build/default/jack_3.o -> build/default/libmyjack.a
[7/8] static_link: build/default/automationtrack_2.o -> build/default/libautomationtrack.a
[8/8] cxx_link: build/default/main_4.o -> build/default/test.out
Traceback (most recent call last):
  File "/home/milk/src/AutoMate/.waf3-1.5.10-470a6353112b965a8e14982b8c571494/wafadmin/Scripting.py", line 289, in build_impl
    bld.compile()
  File "/home/milk/src/AutoMate/.waf3-1.5.10-470a6353112b965a8e14982b8c571494/wafadmin/Build.py", line 168, in compile
    self.save()
  File "/home/milk/src/AutoMate/.waf3-1.5.10-470a6353112b965a8e14982b8c571494/wafadmin/Build.py", line 112, in save
    cPickle.dump(data,file)
AttributeError: Can't pickle local object 'BuildContext.__init__.<locals>.node_class'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./waf", line 153, in <module>
  File "/home/milk/src/AutoMate/.waf3-1.5.10-470a6353112b965a8e14982b8c571494/wafadmin/Scripting.py", line 105, in prepare
    prepare_impl(t,cwd,ver,wafdir)
  File "/home/milk/src/AutoMate/.waf3-1.5.10-470a6353112b965a8e14982b8c571494/wafadmin/Scripting.py", line 98, in prepare_impl
    main()
  File "/home/milk/src/AutoMate/.waf3-1.5.10-470a6353112b965a8e14982b8c571494/wafadmin/Scripting.py", line 133, in main
    fun(ctx)
  File "/home/milk/src/AutoMate/.waf3-1.5.10-470a6353112b965a8e14982b8c571494/wafadmin/Scripting.py", line 277, in build
    return build_impl(bld)
  File "/home/milk/src/AutoMate/.waf3-1.5.10-470a6353112b965a8e14982b8c571494/wafadmin/Scripting.py", line 292, in build_impl
    info("Waf: Leaving directory `%s'"%bld.bldnode.abspath())
  File "/home/milk/src/AutoMate/.waf3-1.5.10-470a6353112b965a8e14982b8c571494/wafadmin/Node.py", line 281, in abspath
    ret=self.__class__.bld.cache_node_abspath[variant].get(self.id,None)
AttributeError: 'NoneType' object has no attribute 'cache_node_abspath'
./waf  24.75s user 2.75s system 262% cpu 10.463 total
```

**Comment by harryhaaren** [comment]
Hi,

I think the issue is that Waf requires Python 2.x to run, while your system probably has Python 3.x as a default. Try running the following commands to compile;
```
python2 ./waf configure
python2 ./waf
```
That builds fine here - but please report back if there was an issue compiling with Python2.

On a side-note, I don't really recommend using this software - its very old, outdated, and there are probably better alternatives to use :)

Regards, -Harry

**Comment by mxmilkiib** [comment]
Ah yes, that works :) Thanks!

I've exploring projects that use JACK Transport atm. I don't think there's quite anything as basic/modular as this app, though I'll be sticking with sequencer64 given lack of live recording.
